"""empty message

Revision ID: 0d8a92509856
Revises: 77a4376cea08
Create Date: 2023-10-02 11:09:13.662631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8a92509856'
down_revision = '77a4376cea08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('typ_vozidla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vyrobce_vozidla', sa.String(length=30), nullable=True),
    sa.Column('vyrobce_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vyrobce_id'], ['vyrobce.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vyrobce', schema=None) as batch_op:
        batch_op.alter_column('vyrobce_vozidla',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vyrobce', schema=None) as batch_op:
        batch_op.alter_column('vyrobce_vozidla',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    op.drop_table('typ_vozidla')
    # ### end Alembic commands ###
